### ISSUE TITLE
Upgrading to 1.1.0 causes build to fail

### ISSUE THREAD

**Issue by kdubb** [kordamp/jandex-gradle-plugin#25] opened 2023-02-22 04:44 UTC
When I change from `1.0.0` to `1.1.0` I get the following error:

```
Caused by: java.lang.ClassCastException: class org.kordamp.gradle.plugin.jandex.Banner$Inject cannot be cast to class org.kordamp.gradle.plugin.jandex.Banner (org.kordamp.gradle.plugin.jandex.Banner$Inject is in unnamed module of loader org.gradle.internal.classloader.VisitableURLClassLoader @2bab28a6; org.kordamp.gradle.plugin.jandex.Banner is in unnamed module of loader org.gradle.internal.classloader.VisitableURLClassLoader @146b18e4)
        at org.kordamp.gradle.plugin.jandex.JandexPlugin.apply(JandexPlugin.groovy:45)
        at org.kordamp.gradle.plugin.jandex.JandexPlugin.apply(JandexPlugin.groovy)
        at org.gradle.api.internal.plugins.ImperativeOnlyPluginTarget.applyImperative(ImperativeOnlyPluginTarget.java:43)
        at org.gradle.api.internal.plugins.RuleBasedPluginTarget.applyImperative(RuleBasedPluginTarget.java:51)
        at org.gradle.api.internal.plugins.DefaultPluginManager.addPlugin(DefaultPluginManager.java:187)
        at org.gradle.api.internal.plugins.DefaultPluginManager.access$100(DefaultPluginManager.java:52)
        at org.gradle.api.internal.plugins.DefaultPluginManager$AddPluginBuildOperation.run(DefaultPluginManager.java:282)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:47)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:68)
        at org.gradle.api.internal.plugins.DefaultPluginManager.lambda$doApply$0(DefaultPluginManager.java:167)
        at org.gradle.configuration.internal.DefaultUserCodeApplicationContext.apply(DefaultUserCodeApplicationContext.java:44)
        at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:166)
        ... 174 more
```

Running with `--quiet` seems to get past the error.

**Comment by kdubb** [comment] 2023-02-22 04:45
It's a Quarkus `2.15` project using Gradle `7.5.1`

**Comment by kdubb** [comment] 2023-02-22 05:11
I just realized this is only in a single module of a multi-module project. The projects has 8 modules 2 of which apply Jandex. If I remove it from the module that generates the error and leave it in the other module the build still works fine.

**Comment by aalmiray** [comment] 2023-03-30 12:17
Do you have a reproducible repository you may link to?

**Comment by kiwi-oss** [comment] 2023-03-31 19:50
Thanks for looking into it. Next week, I will create a minimal reproducible project and link to it.

**Comment by briancullen** [comment] 2024-03-10 08:48
I had a similar problem, which is how I found this issue. Eventually I found putting the following at the top of the root `build.gradle.kts` (I'm using kotlin instead of groovy) sorted it out. For groovy I think the only change you need to make is remove the second line where we define the value.

I currently don't know why this solved my problem and it is possible that is is something to do with my setup. I have not tried it with the reproducer but it might be worth trying if you are stuck. For reference this was not necessary if I was using version `1.0.0` of the jandex plugin, this is using gradle 8.6 and quarkus 3.8.2.

```
buildscript {
    val quarkusPluginVersion: String by project
    repositories {
        gradlePluginPortal()
    }

    dependencies {
        classpath("io.quarkus:io.quarkus.gradle.plugin:$quarkusPluginVersion")
    }
}
```

**Comment by guitcastro** [comment] 2024-12-03 18:22
Same problem here, any updates?

**Comment by aalmiray** [comment] 2024-12-03 21:37
Well, have you tried with the latest version, `2.1.0`? https://github.com/kordamp/jandex-gradle-plugin/releases/tag/v2.1.0

**Comment by guitcastro** [comment] 2024-12-03 22:02
@aalmiray yes, unfortunately got the same error

**Comment by aalmiray** [comment] 2024-12-04 10:02
I can confirm the problem still occurs with latest versions.

**Comment by aalmiray** [comment] 2024-12-04 17:40
There is nothing to be fixed on the plugin side _unless_ the `Banner` class is changed back to a regular type and not a Gradle build service, which kind of defeats the purpose of build services in the first case. 

The issue is caused by the class being loaded by multiple classloaders, tracked by https://github.com/gradle/gradle/issues/17559

There is a workaround: add the plugin with `apply false` to the root project or to `pluginManagement` in `settings.gradle`.

Because of this no work will be performed on the plugin, as any other plugin using build services in a similar way will exhibit the same behavior. This is a core Gradle issue that should be addressed by the Gradle team.

**Closed** 2024-12-04 17:40 UTC

**Comment by RamAnvesh** [comment] 2025-12-10 14:58
Would this comment be relevant to this issue? :
https://github.com/gradle/gradle/issues/17559#issuecomment-869661081
