### ISSUE TITLE
gradle 7

### ISSUE THREAD

**Issue by natros** [kordamp/jandex-gradle-plugin#11] opened 2021-05-15 19:39 UTC
gradle 7.0.2 complains about implicit dependency
```
Task :dao:compileTestJava
Execution optimizations have been disabled for task ':dao:compileTestJava' to ensure correctness due to the following reasons:
  - Gradle detected a problem with the following location: '/Users/fsousa/Projects/ipb/gdoc2/dao/build/resources/main'. Reason: Task ':dao:compileTestJava' uses this output of task ':dao:jandex' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.0.2/userguide/validation_problems.html#implicit_dependency for more details about this problem.
```

**Comment by aalmiray** [comment] 2021-05-15 19:44
Probable duplicate of #9

**Comment by aalmiray** [comment] 2021-05-15 19:45
@natros are you using version `0.10.0` of the `jandex-gradle-plugin`? If so then the fox for #9 is not complete.
Could you post the result of invoking `gradle --version` (or `gradlew --version` if using the wrapper).

**Comment by natros** [comment] 2021-05-15 19:49
```
------------------------------------------------------------
Gradle 7.0.2
------------------------------------------------------------

Build time:   2021-05-14 12:02:31 UTC
Revision:     1ef1b260d39daacbf9357f9d8594a8a743e2152e

Kotlin:       1.4.31
Groovy:       3.0.7
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          16.0.1 (Oracle Corporation 16.0.1+9-24)
OS:           Mac OS X 10.15.7 x86_64
```

**Comment by aalmiray** [comment] 2021-05-15 20:33
Current workaround is to add `test.dependsOn(jandex)`

**Comment by natros** [comment] 2021-05-15 20:59
not working :(

[jandex-demo.zip](https://github.com/kordamp/jandex-gradle-plugin/files/6488200/jandex-demo.zip)

**Comment by aalmiray** [comment] 2021-05-16 10:47
If you change it to the following it will

```groovy
tasks.named('compileTestJava') {
  dependsOn(jandex)
}

tasks.named('test') {
  useJUnitPlatform()
  dependsOn(jandex)
}
```

**Comment by natros** [comment] 2021-05-16 12:40
it's working

thank you!

**Closed** 2021-12-25 16:11 UTC

**Comment by huw0** [comment] 2022-09-18 15:39
With gradle 7.5.1, the workaround above is throwing an error...

```
> Cannot convert extension 'jandex' to a task.
  The following types/formats are supported:
    - A String or CharSequence task name or path
    - A Task instance
    - A TaskReference instance
    - A Buildable instance
    - A TaskDependency instance
    - A Provider that represents a task output
    - A Provider instance that returns any of these types
    - A Closure instance that returns any of these types
    - A Callable instance that returns any of these types
    - An Iterable, Collection, Map or array instance that contains any of these types
```

Quoting jandex fixes the problem.

```
tasks.named('compileTestJava') {
    dependsOn 'jandex'
}

tasks.named('test') {
    dependsOn 'jandex'
}
```
